name: Publish on GitHub & Modrinth

on: [ pull_request, workflow_dispatch ]

jobs:
  build:

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: Kir-Antipov/mc-publish@v3.3
        with:

          modrinth-id: VYegjBEm
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}


          github-token: ${{ secrets.GITHUB_TOKEN }}